default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: my_academy_quest_test

production:
  primary:
    <<: *default
    host: <%= ENV['DB_PROD_HOST'] %>
    port: <%= ENV['DB_PROD_PORT'] %>
    username: <%= ENV['DB_PROD_USERNAME'] %>
    password: <%= ENV['DB_PROD_PASSWORD'] %>
    database: <%= ENV['DB_PROD_NAME'] %>

  cache:
    <<: *default
    host: <%= ENV['DB_PROD_HOST'] %>
    database: my_academy_quest_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    host: <%= ENV['DB_PROD_HOST'] %>
    database: my_academy_quest_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    host: <%= ENV['DB_PROD_HOST'] %>
    database: my_academy_quest_cable
    migrations_paths: db/cable_migrate